version: 2
jobs:
   one:
      docker:
        - image: rsridivya/hello
      steps:
        - checkout
        - run: echo "A first hello world"
   two: 
      docker:
        - image: rsridivya/hello
      steps:
        - checkout
        - run: echo "Second hello world"
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two


